version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
        environment:          
          TERM: xterm
    working_directory: ~/test-web-js
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Cypress Run
          command: ./node_modules/.bin/cypress-tags run -e TAGS='@instagram'
      - store_artifacts:
          path: ~/test-web-js/cypress/screenshots
      - store_artifacts:
          path: ~/test-web-js/cypress/videos